repos:
  - repo: local
    hooks:
      - id: security
        name: Run security check
        files: .*\.(js|jsx|vue|ts|json|html)$
        language: system
        entry: pnpm security:check
        pass_filenames: false

      - id: lint
        name: Run linter
        files: .*\.(js|jsx|vue|ts|json|html)$
        language: system
        entry: pnpm lint
        pass_filenames: false

      - id: prettier
        name: Run formatter
        files: .*\.(js|jsx|vue|ts|json|html)$
        language: system
        entry: pnpm format
        pass_filenames: false

      - id: build
        name: Run build
        files: .*\.(js|jsx|vue|ts|json|html)$
        language: system
        entry: pnpm build
        pass_filenames: false


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Run trailing-whitespace

      - id: end-of-file-fixer
        name: Run end-of-file-fixer

      - id: check-yaml
        name: Run check-yaml

      - id: check-added-large-files
        name: Run check-added-large-files


  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: forbid-crlf
        name: Forbid CRLF line endings
        exclude: \.(txt|lock)$

      - id: remove-crlf
        name: Remove CRLF line endings
        exclude: \.(txt|lock)$


  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
